dbt_production_profile:
  target: dev
  
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('NEON_HOST') }}"
      user: "{{ env_var('NEON_USER') }}"
      password: "{{ env_var('NEON_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('NEON_DB') }}"
      schema: silver_dev  
      threads: 4
      sslmode: require        # عشان Neon يقبل الاتصال
      keepalives_idle: 30     # نبضة عشان Neon ميقفلش السكة
      connect_timeout: 10

    prod:
      type: postgres
      host: "{{ env_var('NEON_HOST') }}"
      user: "{{ env_var('NEON_USER') }}"
      password: "{{ env_var('NEON_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('NEON_DB') }}"
      schema: silver_prod  
      threads: 8
      sslmode: require        # لازم هنا كمان
      keepalives_idle: 30     # وتم إضافتها هنا بناء على مراجعتك
      connect_timeout: 10